### ISSUE TITLE
Non-standard binary installer script

### ISSUE THREAD

**Issue by hughperkins** [MoonchildProductions/PM4Linux-installer#19]
Using a binary-script as an installer script is non-standard and unusual.

In the specific, it makes installing palemoon in Docker non-trivial, gives error messages.

(By the way, you might be wondering why I'm installing it in Docker, rather than just in my base system; and the answer is related: the installer is opaque, non-transparent, and requires root.  I'm not very keen on running this directly on my host system.  Sorry)

**Comment by wolfbeast** [comment]
Are you just going through and opening issues for what you consider "non-standard and unusual"? If so, I'd kindly ask you to stop. 

If you don't like the installer, you can use the standard bzipped tarball as well, which is not opaque, does not require root, and should allow you to plant the browser anywhere and integrate it in your launcher of choice any "standard" way you prefer. The installer is a convenience application, and is fully open source - you can see exactly what it does in this very repository. If you don't trust the packaged version, you can even build it yourself.

Closing this non-issue.
