### ISSUE TITLE
Error whilst installing into Docker

### ISSUE THREAD

**Issue by hughperkins** [MoonchildProductions/PM4Linux-installer#20]
Error whilst installing into Docker.  Dockerfile as follows:

```
FROM ubuntu:14.04

WORKDIR /root
RUN apt-get install -y tar bzip2
COPY pminstaller.sh pminstaller.sh
RUN chmod +x pminstaller.sh
RUN ls -lh
RUN ./pminstaller.sh
```

What I expect to happen:
- palemoon installs

What actually happens:
```
Step 10 : RUN ./pminstaller.sh
 ---> Running in 71fcbcec5f0e
tar (grandchild): xz: Cannot exec: No such file or directory
tar (grandchild): Error is not recoverable: exiting now
tar: Child died with signal 13
tar: Error is not recoverable: exiting now
The command '/bin/sh -c ./pminstaller.sh' returned a non-zero code: 2
```

**Comment by squarefractal** [comment]
You don't have xz installed, please install it.

**Comment by hughperkins** [comment]
Yes, actually I got way past that:
```
FROM ubuntu:14.04

RUN apt-get update
RUN pwd
WORKDIR /root
RUN pwd
RUN ls
RUN ls
RUN apt-get install -y tar bzip2 xz-utils
RUN apt-get install -y libgtk2.0-0
RUN apt-get install -y x11vnc xvfb
RUN mkdir ~/.vnc
RUN x11vnc -storepasswd aaaa ~/.vnc/passwd
EXPOSE 5900


RUN ls -lh /
RUN ls -lh /tmp
COPY pminstaller.sh pminstaller.sh
RUN chmod +x pminstaller.sh
RUN ls -lh
# RUN Xvfb :1 -screen 0 1024x768x16 & && export DISPLAY=:1.0 && ./pminstaller.sh
RUN start-stop-daemon --start --background --exec /usr/bin/Xvfb -- :1 -screen 0 1024x768x16 -ac +extension GLX +render -noreset -extension RANDR  && ps -ef && sleep 3 && export DISPLAY=:1.0 && ./pminstaller.sh
```

However, cannot get past the non-standard sudo dialog.  firefox can be installed, without needing any non-standard sudo dialogs, but palemoon cannot be.  For now, I reckon that firefox for all its issues is actually less of a security risk :-(

**Comment by wolfbeast** [comment]
As I stated in the other issue you opened: you don't have to use the installer which is designed for interactive desktop use. You can grab and use the bzipped tarball instead and automate its installation (unpack + shortcut) in your script easily instead of trying to force your hand with the installer that was not design for your use case.
