### ISSUE TITLE
Installer attempts to access non-palemoon config directory

### ISSUE THREAD

**Issue by mattok** [MoonchildProductions/PM4Linux-installer#21]
When I update PaleMoon using the pm4linux-installer (latest version, 0.2.1) I get:

    (yad:15602): IBUS-WARNING **: The owner of /home/username/.config/ibus/bus is not root!

- Why is the installer trying to access the `/home/username/.config/ibus` directory? It would seem that this has nothing to do with the installation of pale moon, and so it is likely to be a bug.

- It is to be expected that the .config directory and files/directories within it are owned by the local user - not by root, so why was the installer expecting it to be owned by root? This seems to be a related bug.

**Comment by squarefractal** [comment]
This is a warning arising from the use of ibus (by yad) as a root user while still having `$HOME` set to that of the unprivileged user, and finding ibus configuration files that are owned by a different user.

The installer scripts themselves are not trying to access or modify any files in `$HOME/.config`, so it's not something that can be helped.

**Comment by mattok** [comment]
I've taken a bit of a closer look and I'm not so sure about it being something that can't be helped.

Yad is used by the installer script to produce GTK+ dialogs. You state that the pm4linux-installer is running yad as root. This is probably the root cause of the problem. I don't think it needs to do this, nor that it should be doing this. I would have thought that the only thing the installer needs to do as root is perform the file operations required to install the application. Is it possible the script could be altered to achieve this please?

Thank you.

**Comment by squarefractal** [comment]
[**@mattok**](https://github.com/mattok) commented on [Saturday, January 30, 2016 4:52:20 AM](https://github.com/MoonchildProductions/PM4Linux-installer/issues/21#issuecomment-177014429 "2016-01-29T23:22:20Z - Replied by Github Comment Enhancer"):
> Is it possible the script could be altered to achieve this please?

This would require elevating multiple times for each action, which won't be even feasible on systems that only use su, since the user would be prompted for a password each time something needs to be performed as superuser.

**Comment by mattok** [comment]
Sorry, but I don't really follow.

Personally, I only ever use the script to undertake one action, and then I quit: The first time I used it I installed the latest version. I've since used it to upgrade palemoon. In future, if palemoon development takes an odd turn, I might choose to uninstall/delete it.

I can't see why you'd ever need or want to undertake more than one action that would require root access... and if I ever did, I wouldn't mind entering my password again.

I don't know what anyone else thinks, but I'd much rather enter my password a few times than have programs run as root that needn't. If there is something that could be done about this, I'd be most grateful.

**Comment by wolfbeast** [comment]
Sorry but from a user's point of view, only one action is started: "install Pale Moon". the user shouldn't be asked for the root password more than once, no matter how many steps the script has to perform for the individual installation steps. this means that the installer should only elevate once, and do everything it needs to do from that elevated session in one go.

**Comment by mattok** [comment]
I appreciate the effort that has gone into creating and maintaining pm4linux-installer, but it appears that it's not for me. I suppose this issue will remain an issue for anyone using ibus for multiple language support, but the right thing to do appears to be to close it. Thank you for your responses.

**Comment by mattok** [comment]
I appreciate the effort that has gone into creating and maintaining pm4linux-installer, but it appears that it's not for me. I suppose this issue will remain an issue for anyone using ibus for multiple language support, but the right thing to do appears to be to close it. Thank you for your responses.

**Comment by mattok** [comment]
I appreciate the effort that has gone into creating and maintaining pm4linux-installer, but it appears that it's not for me. I suppose this issue will remain an issue for anyone using ibus for multiple language support, but the right thing to do appears to be to close it. Thank you for your responses.

**Comment by mattok** [comment]
I appreciate the effort that has gone into creating and maintaining pm4linux-installer, but it appears that it's not for me. I suppose this issue will remain an issue for anyone using ibus for multiple language support, but the right thing to do appears to be to close it. Thank you for your responses.

**Comment by mattok** [comment]
Thank you for your responses. I appreciate the effort that has gone into creating and maintaining pm4linux-installer, but it appears that it's not for me.

**Comment by mattok** [comment]
Thank you for your responses. I appreciate the effort that has gone into creating and maintaining pm4linux-installer, but it appears that it's not for me.

**Comment by mattok** [comment]
Thank you for your responses. I appreciate the effort that has gone into creating and maintaining pm4linux-installer, but it appears that it's not for me.
