### ISSUE TITLE
Installer/Updater for FossaMail

### ISSUE THREAD

**Issue by EddJuglans** [MoonchildProductions/PM4Linux-installer#22]
Please excuse me if this question is in the wrong section. I want to ask if it's possible to modify Pale Moon's pminstaller.sh file to include FossaMail install/update functions. I use both PaleMoon and FossaMail, and whilst updating Pale Moon is a breeze with pminstaller.sh, updating FossaMail is still a bit of a pain.

Kind regards,
Edd...

**Comment by trav90** [comment]
Closing this as FossaMail has been discontinued.
